### ISSUE TITLE
Logbook 2

### ISSUE THREAD

**Issue by Anusharai20** [Anusharai20/fyp-The-Pet-Poochery#3]
# Logbook 2

Meeting No: 2
Date: 2024-11-24
Start Time: 11A.M.
End Time: 12:15 P.M.

## Items Discussed

1.  Logbook - 1 issues review

     -  The problem with Logbook-1 was reported not complete, and suggestions for what and how to write were provided
     -  Discussed about the issues in showing the relationships in my entity relationship diagram (ERD) and got feedback on how and where to make improvements

2. About Github

     -  Discussed to add commit links in GitHub issues to track specific changes related to tasks
     -  Discussed about  uploading the logbook signed by the supervisor in the comment section of the particular issue
    
3. Visual Studio Code Extensions and Language Server Protocol(LSP)
     - Discussed  installing the extensions in VS Code for easily detecting the syntax errors, making code well-structured and readable, and providing auto-completion for increasing the code efficiency.
     - Discussed the features and installation of the Language Server Protocol (LSP) for providing language-specific features like code completion, syntax highlighting, and error and warning marking. 
4. Debugging Tools 
     -  Discussed the debugging tools and uses of breakpoints for marking the pause for execution for debugging, which was demonstrated through a demo of debugging in Express.js.

5.  Assignment Submission Tracking Program
     -  Learned and received a demo about a program in Rust, JavaScript, and TypeScript that checks assignment submissions, tracks whether they were submitted, and automates downloads from GitHub repositories.

## Achievements
     - [ ]  Install Language Server Extensions for react.js and node.js in VS Code. If there is a syntax error, the editor should catch it. Autocomplete is desired
     - [ ] Successfully installed, set up and enabled -----(a debugging package). And also researched ways to debug in react.js and node.js and how to use it
     - [ ]  A database was successfully established, tables, models, controllers, and migrations for defined entities were constructed, and relationships, data types, and enum values were defined.

## Problem(if any):

 1.  Initializing Database Schema:
     - 

 2.  Setting up Debugging tool : 
     

## Tasks for the Next Meeting
      

-  Wireframes for the login, sign-in and home page.
-  Insert fake/dummy data in the tables by using factory and seeding.
-  Research and write simple test cases related to CRUD(create, read, update and delete) operation.
